# Generated by Django 5.2.7 on 2025-10-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genetic_features', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureselection',
            name='algorithm_type',
            field=models.CharField(default='basic', max_length=50),
        ),
        migrations.AddField(
            model_name='featureselection',
            name='detailed_results',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
